build/talend.studio.tos.product.parent.pom/pom.xml

Should remove the ".settings" folder. also remove the wrong folder "repository" which was fixed for "maven_repository.zip" in commit https://github.com/Talend/tcommon-studio-se/commit/ef341562357d68c058821bcb33f51b9a96eceff8 .

TDI-33874: The build didn't delete the configration settings folder.

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

bug fixed TDQ-11187 modify org.talend.dataquality.sampling version from

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

https://jira.talendforge.org/browse/TDI-36957

TDI-36957: Add new delimited components to studio

---

build/dependencies.p2/pom.xml
build/pom.xml
build/talend.studio.tos.all.p2.product/pom.xml
build/talend.studio.tos.product.parent.pom/pom.xml
pom.xml
talend.studio.parent.pom/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [master]

---

build/dependencies.p2/pom.xml
build/pom.xml
build/talend.studio.tos.all.p2.product/pom.xml
build/talend.studio.tos.product.parent.pom/pom.xml
pom.xml
talend.studio.parent.pom/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.3]

---

build/dependencies.p2/pom.xml
build/pom.xml
build/talend.studio.tos.all.p2.product/pom.xml
build/talend.studio.tos.product.parent.pom/pom.xml
pom.xml
talend.studio.parent.pom/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.2]

---

build/dependencies.p2/pom.xml
build/pom.xml
build/talend.studio.tos.all.p2.product/pom.xml
build/talend.studio.tos.product.parent.pom/pom.xml
pom.xml
talend.studio.parent.pom/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.1]

---

build/pom.xml
build/talend.studio.tos.all.p2.product/pom.xml
build/talend.studio.tos.product.parent.pom/pom.xml
pom.xml
talend.studio.parent.pom/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.0]

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

updated the dependencies version for json-io

fix(migration):update json-io

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

should be merged after Talend/components#597

TBD-4656: add new hadoop cluster configuration input component

---

build/talend.studio.tos.all.p2.product/talend.product

Hi, 
Please reivew this PR to add the ESB EE test feature
Thanks,
Yi

TESB-19962: Add esbenterprise test feature

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

* Move components-ee to enterprise repo

chore(TDI-39398): move components-ee

---

build/dependencies.p2/dependencies.p2.tos/pom.xml
build/dependencies.p2/pom.xml

* Move components-ee to enterprise repo

chore(TDI-39398): move components-ee (#73)

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

https://jira.talendforge.org/browse/TDI-38416

chore(TDI-38416): split Marketo modules

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

- also integrate JDBC TDI-39241

feat(TDI-39875): integrate Marklogic

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

chore(Jenkins): update DQ libs to 1.6.6-SNAPSHOT, please help review it!

chore(Jenkins): update DQ libs to 1.6.6-SNAPSHOT

---

build/talend.studio.tos.product.parent.pom/pom.xml

https://jira.talendforge.org/browse/TUP-19969

fix(TUP-19969): Eclipse upgrade - TOS need to work with eclipse 4.7.0

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

Need to align commons-compress library in the scope of:
https://jira.talendforge.org/browse/TDI-42834

fix(TDI-42834): update commons-compress lib version

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

https://jira.talendforge.org/browse/TDI-42834
+ 
https://jira.talendforge.org/browse/TDI-43050
Backport to 7.2

fix(TDI-42834): upgrade commons-compress to latest version

---

build/talend.studio.tos.bd.product/config.ini

https://jira.talendforge.org/browse/TDI-43300

fix(TDI-43300): fix tacokit component jar clash with locales

---

build/dependencies.p2/pom.xml

chore(Jenkins): Update DQ libs to 7.0.2, please help review it!

chore(Jenkins): Update DQ libs to 7.0.2

---

talend.studio.parent.pom/pom.xml

Upgrade components version to 0.28.6

chore: upgrade tcomp v0 version 0.28.6

---

build/dependencies.p2/pom.xml

chore(Jenkins): Update DQ libs to 7.0.3-SNAPSHOT, please help review it!

chore(Jenkins): Update DQ libs to 7.0.3-SNAPSHOT

---

talend.studio.parent.pom/pom.xml

Bump components to 0.28.8

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

https://jira.talendforge.org/browse/TDI-44770
Upgrade snakeyaml version.

chore(TDI-44770): upgrade snakeyaml version

---

build/talend.studio.tos.bd.product/config.ini

https://jira.talendforge.org/browse/TDI-45347

chore(TDI-45347) : bump connectors 1.16.0

---

build/talend.studio.tos.bd.product/config.ini

https://jira.talendforge.org/browse/TDI-45339

chore(TDI-45339): Bump TCK comp version

---

build/talend.studio.tos.bd.product/config.ini

https://jira.talendforge.org/browse/TDI-45607

fix(TDI-45607) Upgrade tck in studio

---

build/dependencies.p2/dependencies.p2.tos/pom.xml

Reverts Talend/studio-se-master#378

Revert "Nrousseau/73 tup 27154 beanutils"

---

talend.studio.parent.pom/pom.xml

For Jira: https://jira.talendforge.org/browse/TDI-46033

fix(TDI-46033): bump tcompv0 connectors to 0.31.0

---

talend.studio.parent.pom/pom.xml

https://jira.talendforge.org/browse/TDI-46033
bump tcompv0 for master

fix(TDI-46033): bump tcompv0 connectors to 0.32.0-SNAPSHOT

---

talend.studio.parent.pom/pom.xml

https://jira.talendforge.org/browse/TDI-46260

fix(TDI-46260): bump tcompv0 connectors to 0.33.0-SNAPSHOT

---

talend.studio.parent.pom/pom.xml

https://jira.talendforge.org/browse/TDI-46260

fix(TDI-46260): bump tcompv0 connectors to 0.32.1

---

talend.studio.parent.pom/pom.xml

https://jira.talendforge.org/browse/TDI-46399

fix(TDI-46260): bump tcompv0 connectors to 0.33.0

---

talend.studio.parent.pom/pom.xml

https://jira.talendforge.org/browse/TUP-40916

chore(TUP-40916): Studio issues if Java version is > Java 17
